language: cpp

install:
  - sudo apt-get update
  - sudo apt-get install --only-upgrade cmake
before_script:
  - git submodule init
  - git submodule update

script:
  - mkdir build
  - cd build
  - cmake ../
  - make
  - make test
