language: cpp

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5

before_install:
  - wget https://cmake.org/files/v3.4/cmake-3.4.0-Linux-x86_64.tar.gz 
  - tar -xzf cmake-3.4.0-Linux-x86_64.tar.gz

before_script:
  - git submodule init
  - git submodule update

script:
  - mkdir build
  - cd build
  - ../cmake-3.4.0-Linux-x86_64/bin/cmake ../ && make && make test
