language: cpp

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5

before_install:
  - wget --no-check-certificate https://cmake.org/files/v3.4/cmake-3.4.0-Linux-x86_64.tar.gz 
  - tar -xzf cmake-3.4.0-Linux-x86_64.tar.gz
  - export PATH="$(readlink -f cmake-3.4.0-Linux-x86_64/bin/):$PATH"

before_script:
  - git submodule init
  - git submodule update

script:
  - mkdir build
  - cd build
  - export CC=gcc-5
  - export CXX=g++-5
  - cmake ../ && make && CTEST_OUTPUT_ON_FAILURE=TRUE make test
